### ISSUE TITLE
Doesn't work with data from the server

### ISSUE THREAD

**Issue by msouidi309** [amsik/liquor-tree#20]
Hi, thanks for this tool, it's amazing.
Unfortunately, i have a little problem , 
It doesn't work with dynamic data, maybe something i made wrong ? Here is my code 

```
<template>
<tree
        ref="tree"
        :data="treeData"
  />
</template>
```

```
<script>
...
    data: () => ({
      treeData: []
    }),
    mounted: function () {
       this.getTreeData()
    },
    methods: {
       getTreeData() {
             var self = this
             axios.get('http://localhost:8082/files')
             .then((response) => {
                       self.treeData = response.data
              })
             .catch((err) => {
                console.log('Error : ' + err)
             })
       }
...
</script>
```

Thank you !

**Comment by amsik** [comment]
You should not change directly `treeData` property. Try this way: https://amsik.github.io/liquor-tree/#Async-Data

**Comment by msouidi309** [comment]
I just tried, i tried like that : 
```
<tree ref="tree" :options="treeOptions"
/>
```

```
data: () => ({
  treeFilter: '',
  treeOptions: {
       checkbox: true,
       fetchData() {
           return axios.get('http://localhost:8082/files')
        }
   }
```
And it displayed just the root folder, not the entire tree

**Comment by amsik** [comment]
Could you show me the response of the request?

**Comment by ijpatricio** [comment]
Hello all, 

First of all, thanks @amsik for great component!

I just faced same problem.. And still didn't finish the feature... but by analyzing vue dev tools...

the model of each node coming from database,, has an "id" attribute.. which will most likely collide with internal feature

![image](https://user-images.githubusercontent.com/26031459/41352034-261d63b8-6f10-11e8-972b-cecabf4796ff.png)

I will confirm this very soon I'm working on it...

Like, so many databases uses "id" as primary key, a simple fix could be using _id for internal component reference...

Let's see, speak soon

**Comment by ijpatricio** [comment]
Hello, so I understood now.

The "data" prop passed, gets copied to a new object, 
inside the TreeRoot.vue component (node_modules folder, for backend developers better understanding)

This happens because props are immutable, so to maniputate data, the component copies to internal component "data" key.

After server loading, even computed propertie... the empty array was already copied. Check this by analyzing vue dev tools... the component model key will be empty.

Ok, quick fix. Have the component with a v-if directive

![image](https://user-images.githubusercontent.com/26031459/41352939-b6498848-6f12-11e8-8cce-51b72810f914.png)

This way, "when you will enable it to show", it will mount the component again, and props wil be already set, and properly copied!

PS: Very IMPORTANT to use v-if and not v-show!! v-if detaches from virtual dom on toggling, and v-show only changes style to "display: none"

**Comment by amsik** [comment]
Yeah. You are totally right. I have to copy recieved data to a new object because tree uses a its own structure. I think about adding watchers and get rid of this approach... but I will do it later.

That's why we have a several approaches:
- [Store (Vuex)](https://amsik.github.io/liquor-tree/#Integration-with-Vuex)
- [Async data](https://amsik.github.io/liquor-tree/#Async-Data)
- [API for nodes manipulating](https://amsik.github.io/liquor-tree/#API)
